apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html;

        # Fallback: serve index.html for any path
        location / {
            try_files $uri /index.html;
        }
    }

